title: Bitcoin Core Docker Compilation Project
description: Discover a comprehensive repository of Bitcoin releases since 2009, all within a clean and efficient Docker container for seamless access and management.
show_downloads: false
remote_theme: just-the-docs/just-the-docs
url: https://mocacinno.com
nav_order: 1
has_children: true
search_enabled: true
logo: "/favicon.ico"
aux_links:
  "View on GitHub":
    - "https://github.com/mocacinno/bitcoin_core_docker"
color_scheme: dark
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/mocacinno/bitcoin_core_docker"
gh_edit_branch: "main"
gh_edit_view_mode: "edit"
plugins:
  - jekyll-readme-index
  - jekyll-sitemap
enable_copy_code_button: true
mermaid:
  version: "11.12.1"
heading_anchors: true
back_to_top: true
back_to_top_text: "Back to top"
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"
search:
  heading_level: 2
  previews: 4
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
nav_error_report: true
markdown: kramdown
kramdown:
  parse_block_html: true
  parse_span_html: true
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
  html_to_native: true
