title: Bitcoin Core Docker Compilation Project
description: A repository van most major releases back to 2009, inside a clean docker container
show_downloads: false
remote_theme: just-the-docs/just-the-docs
url: https://www.mocacinno.com
nav_order: 1
has_children: true
search_enabled: true
logo: "/favicon.ico"
aux_links:
  "View on GitHub":
    - "https://github.com/mocacinno/bitcoin_core_docker"
color_scheme: dark
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/mocacinno/bitcoin_core_docker"
gh_edit_branch: "main"
gh_edit_view_mode: "edit"
plugins:
  - jekyll-readme-index
  - jekyll-sitemap
  
